import type { ShellTool } from "./GameShell";

/* ── Per-module tools (same 3 for all 8 problems in a module) ── */
export const MODULE_TOOLS: Record<string, ShellTool[]> = {
  "backtracking": [
    { name: "Brute Force",   icon: "✶", cx: "O(nⁿ)", note: "never finishes" },
    { name: "Backtracking",  icon: "↺", cx: "O(n!)",  note: "place · prune",  optimal: true },
    { name: "Bitmask DFS",   icon: "⊞", cx: "O(n!)",  note: "fastest prune" },
  ],
  "graphs": [
    { name: "Recursive DFS", icon: "↓", cx: "O(V+E)", note: "stack overflow" },
    { name: "BFS Queue",     icon: "◎", cx: "O(V+E)", note: "safe & optimal", optimal: true },
    { name: "Union-Find",    icon: "⊍", cx: "O(α·N)", note: "overkill here" },
  ],
  "two-pointers": [
    { name: "Brute Pairs",   icon: "▦", cx: "O(n²)", note: "−20s timer" },
    { name: "Hash Map",      icon: "#", cx: "O(n)",  note: "+extra space" },
    { name: "Two Pointers",  icon: "⇄", cx: "O(n)",  note: "O(1) space",     optimal: true },
  ],
  "sliding-window": [
    { name: "Recompute Each", icon: "↻", cx: "O(n·k)", note: "too slow" },
    { name: "Prefix Sums",   icon: "Σ",  cx: "O(n)",   note: "+extra array" },
    { name: "Sliding Window", icon: "▭", cx: "O(n)",   note: "O(1) space",   optimal: true },
  ],
  "trees": [
    { name: "Linear List",   icon: "≣", cx: "O(n)",     note: "−12s timer" },
    { name: "Sorted Array",  icon: "⇥", cx: "O(n)",     note: "shifts cost" },
    { name: "BST Path",      icon: "⋔", cx: "O(log n)", note: "follow links", optimal: true },
  ],
  "tries": [
    { name: "Hash Set",      icon: "#", cx: "O(m)",   note: "no prefixes" },
    { name: "Sorted List",   icon: "≣", cx: "O(n·m)", note: "slow lookups" },
    { name: "Trie Walk",     icon: "⌥", cx: "O(m)",   note: "shared paths",  optimal: true },
  ],
  "dynamic-programming": [
    { name: "Greedy Grab",   icon: "▾", cx: "O(n)",     note: "wrong answer" },
    { name: "Recursion",     icon: "↯", cx: "O(amtⁿ)",  note: "re-solves all" },
    { name: "DP Table",      icon: "▦", cx: "O(n·k)",   note: "each cell once", optimal: true },
  ],
};

/* ── Per-game mission brief ─────────────────────────────── */
export interface GameMission {
  missionName: string;
  zone: string;
  situation: string;
  objective: string;
  constraint: string;
  sceneLabel: string;
}

export const GAME_MISSIONS: Record<string, Record<number, GameMission>> = {

  "backtracking": {
    1: {
      missionName: "THE ROYAL GUARD",
      zone: "Palace Ruins",
      situation: "Palace Ruins. An 8×8 throne grid under siege.",
      objective: "Post 8 guards so none share a row, column or diagonal.",
      constraint: "A clash forces a backtrack. Prune before you place.",
      sceneLabel: "◇ PALACE RUINS · N-QUEENS PLACEMENT",
    },
    2: {
      missionName: "THE BROKEN PALACE",
      zone: "Palace Ruins",
      situation: "A fractured 5×5 throne grid. Fewer guards, same rules.",
      objective: "Place 5 non-attacking queens on a 5×5 board.",
      constraint: "Rows, columns, and both diagonals must stay clear.",
      sceneLabel: "◇ PALACE RUINS · 5-QUEENS PLACEMENT",
    },
    3: {
      missionName: "QUEENS GUARD",
      zone: "Palace Ruins",
      situation: "A compact 4×4 guardroom. Minimal — but exact.",
      objective: "Place 4 non-attacking queens on a 4×4 board.",
      constraint: "Even one diagonal clash invalidates the formation.",
      sceneLabel: "◇ PALACE RUINS · 4-QUEENS PLACEMENT",
    },
    4: {
      missionName: "SIX SENTINELS",
      zone: "Palace Ruins",
      situation: "A 6×6 throne grid with 6 guard slots.",
      objective: "Place 6 non-attacking queens on a 6×6 board.",
      constraint: "Constraint satisfaction — each placement prunes the tree.",
      sceneLabel: "◇ PALACE RUINS · 6-QUEENS PLACEMENT",
    },
    5: {
      missionName: "SUDOKU BREACH",
      zone: "Palace Ruins",
      situation: "A 9×9 cipher grid — partially filled, fully locked.",
      objective: "Fill every cell so each row, column, and box holds 1–9 exactly once.",
      constraint: "Constraint propagation: place only where no conflict exists.",
      sceneLabel: "◇ PALACE RUINS · CONSTRAINT SATISFACTION",
    },
    6: {
      missionName: "THE LINEUP",
      zone: "Palace Ruins",
      situation: "4 suspects. One correct arrangement matches the evidence.",
      objective: "Swap suspects until their order matches the target arrangement.",
      constraint: "Each swap counts. Minimum swaps = optimal.",
      sceneLabel: "◇ PALACE RUINS · PERMUTATION SEARCH",
    },
    7: {
      missionName: "TREASURE COMBOS",
      zone: "Palace Ruins",
      situation: "A vault of numbered relics. One combination opens the seal.",
      objective: "Select numbers from the pool that sum exactly to the target.",
      constraint: "Overshot = backtrack. No duplicate combinations allowed.",
      sceneLabel: "◇ PALACE RUINS · COMBINATION SUM",
    },
    8: {
      missionName: "WORD HUNT",
      zone: "Palace Ruins",
      situation: "A letter grid concealing a hidden word.",
      objective: "Trace the target word through adjacent cells in the grid.",
      constraint: "Each cell used once. Wrong path = backtrack.",
      sceneLabel: "◇ PALACE RUINS · WORD SEARCH",
    },
  },

  "graphs": {
    1: {
      missionName: "MINEFIELD",
      zone: "Graph Jungle",
      situation: "Graph Jungle. A grid seeded with hidden mines.",
      objective: "Flood-fill every safe cell from your start tile.",
      constraint: "Stop at mines & edges. Visit each cell once.",
      sceneLabel: "◇ GRAPH JUNGLE · BFS FLOOD FROM SOURCE",
    },
    2: {
      missionName: "ISLAND COUNT",
      zone: "Graph Jungle",
      situation: "An ocean grid. Land masses are connected components.",
      objective: "Identify and count every distinct island using DFS.",
      constraint: "Diagonal cells don't connect. Mark every cell of each island.",
      sceneLabel: "◇ GRAPH JUNGLE · CONNECTED COMPONENTS",
    },
    3: {
      missionName: "THE ESCAPE",
      zone: "Graph Jungle",
      situation: "A maze grid. One exit. Shortest path wins.",
      objective: "Reach the exit in the fewest steps using BFS.",
      constraint: "BFS guarantees shortest path. DFS cannot.",
      sceneLabel: "◇ GRAPH JUNGLE · SHORTEST PATH BFS",
    },
    4: {
      missionName: "ROTTEN ORANGES",
      zone: "Graph Jungle",
      situation: "A crate of oranges. Rot spreads one cell per minute.",
      objective: "Find the minimum minutes until all oranges rot — or declare impossible.",
      constraint: "Multi-source BFS. All rotten oranges spread simultaneously.",
      sceneLabel: "◇ GRAPH JUNGLE · MULTI-SOURCE BFS",
    },
    5: {
      missionName: "WALLS AND GATES",
      zone: "Graph Jungle",
      situation: "A dungeon grid. Gates at distance 0. Walls impassable.",
      objective: "Fill each empty room with its distance to the nearest gate.",
      constraint: "BFS from all gates simultaneously. Walls and INF rooms are boundaries.",
      sceneLabel: "◇ GRAPH JUNGLE · MULTI-SOURCE DISTANCE BFS",
    },
    6: {
      missionName: "PACIFIC ATLANTIC",
      zone: "Graph Jungle",
      situation: "A highland grid. Water flows down or equal elevation.",
      objective: "Find every cell from which water can reach both the Pacific and Atlantic.",
      constraint: "Run two reverse-DFS passes — one per ocean. Intersection = answer.",
      sceneLabel: "◇ GRAPH JUNGLE · REVERSE DFS FLOW",
    },
    7: {
      missionName: "WORD LADDER",
      zone: "Graph Jungle",
      situation: "Two words. Change one letter per step, stay valid.",
      objective: "Transform the start word to the end word in the fewest steps.",
      constraint: "Each intermediate word must exist in the dictionary. BFS = shortest.",
      sceneLabel: "◇ GRAPH JUNGLE · BFS ON IMPLICIT GRAPH",
    },
    8: {
      missionName: "CRITICAL LINES",
      zone: "Graph Jungle",
      situation: "A network graph. Some edges, if removed, disconnect the graph.",
      objective: "Identify all bridges (critical edges) using Tarjan's algorithm.",
      constraint: "An edge is a bridge if low[v] > disc[u]. Track discovery and low times.",
      sceneLabel: "◇ GRAPH JUNGLE · TARJAN'S BRIDGE ALGORITHM",
    },
  },

  "two-pointers": {
    1: {
      missionName: "COLLISION COURSE",
      zone: "Pointer Docks",
      situation: "Pointer Docks. A sorted manifest of cargo weights.",
      objective: "Find two crates whose weights sum to the target.",
      constraint: "O(1) space — no hash maps. One scan from both ends.",
      sceneLabel: "◇ POINTER DOCKS · SORTED TWO-SUM",
    },
    2: {
      missionName: "CONTAINER CRAFT",
      zone: "Pointer Docks",
      situation: "Vertical pillars along a dock. Water fills between them.",
      objective: "Find two pillars that trap the maximum water.",
      constraint: "Width × min-height = volume. Two pointers collapse inward.",
      sceneLabel: "◇ POINTER DOCKS · MAX CONTAINER WATER",
    },
    3: {
      missionName: "PALINDROME PRO",
      zone: "Pointer Docks",
      situation: "A string of dock codes. Some read the same backwards.",
      objective: "Verify the string is a palindrome using two pointers.",
      constraint: "Skip non-alphanumeric characters. O(n) time, O(1) space.",
      sceneLabel: "◇ POINTER DOCKS · PALINDROME CHECK",
    },
    4: {
      missionName: "COLOR SORT",
      zone: "Pointer Docks",
      situation: "A cargo sequence of red, white, and blue crates.",
      objective: "Sort them in-place: all reds first, then whites, then blues.",
      constraint: "Dutch National Flag: three pointers, one pass, O(1) space.",
      sceneLabel: "◇ POINTER DOCKS · THREE-WAY PARTITION",
    },
    5: {
      missionName: "TRIPLE SUM",
      zone: "Pointer Docks",
      situation: "A sorted manifest. Find all triplets that sum to zero.",
      objective: "Return every unique triple a + b + c = 0.",
      constraint: "Fix one pointer, two-pointer scan the rest. Skip duplicates.",
      sceneLabel: "◇ POINTER DOCKS · THREE SUM",
    },
    6: {
      missionName: "RAIN TRAP",
      zone: "Pointer Docks",
      situation: "An elevation map. Rain fills between taller walls.",
      objective: "Calculate total water trapped between the elevations.",
      constraint: "Two pointers from ends. Water at position = min(maxL, maxR) − height.",
      sceneLabel: "◇ POINTER DOCKS · TRAPPING RAIN WATER",
    },
    7: {
      missionName: "MERGE STREAMS",
      zone: "Pointer Docks",
      situation: "Two sorted cargo streams arriving at the dock.",
      objective: "Merge both sorted arrays into one sorted array.",
      constraint: "Compare heads, advance the smaller pointer. O(m+n) time.",
      sceneLabel: "◇ POINTER DOCKS · SORTED MERGE",
    },
    8: {
      missionName: "SQUEEZE PLAY",
      zone: "Pointer Docks",
      situation: "A sorted sequence. Squares must stay sorted after squaring.",
      objective: "Return the squares of each element in sorted order.",
      constraint: "Two pointers from ends — largest squares are at the extremes.",
      sceneLabel: "◇ POINTER DOCKS · SORTED SQUARES",
    },
  },

  "sliding-window": {
    1: {
      missionName: "MAX SLIDER",
      zone: "Scanner District",
      situation: "Scanner District. A stream of signal readings.",
      objective: "Find the maximum in every window of size k.",
      constraint: "Deque holds candidates in decreasing order. Pop stale front.",
      sceneLabel: "◇ SCANNER DISTRICT · SLIDING WINDOW MAXIMUM",
    },
    2: {
      missionName: "THE SCANNER",
      zone: "Scanner District",
      situation: "A live signal stream. Find the highest-sum k-length window.",
      objective: "Return the maximum average of any subarray of length k.",
      constraint: "One pass: subtract left, add right. O(n) — no nested loops.",
      sceneLabel: "◇ SCANNER DISTRICT · MAX AVERAGE SUBARRAY",
    },
    3: {
      missionName: "ANAGRAM HUNT",
      zone: "Scanner District",
      situation: "A text stream. A pattern is hiding inside it.",
      objective: "Find the starting index of every anagram of the pattern.",
      constraint: "Fixed-size window = size of pattern. Compare frequency maps.",
      sceneLabel: "◇ SCANNER DISTRICT · FIND ALL ANAGRAMS",
    },
    4: {
      missionName: "LONGEST RUN",
      zone: "Scanner District",
      situation: "A binary signal. Find the longest stretch of 1s.",
      objective: "Find the longest subarray of 1s after deleting exactly one element.",
      constraint: "Expand right freely, shrink left when zeroes exceed 1.",
      sceneLabel: "◇ SCANNER DISTRICT · LONGEST SUBARRAY",
    },
    5: {
      missionName: "FRUIT BASKET",
      zone: "Scanner District",
      situation: "A row of fruit trees. Each basket holds one type.",
      objective: "Find the longest subarray with at most 2 distinct types.",
      constraint: "Expand right, shrink left when distinct types exceed 2.",
      sceneLabel: "◇ SCANNER DISTRICT · AT MOST K DISTINCT",
    },
    6: {
      missionName: "K SWAPS",
      zone: "Scanner District",
      situation: "A binary string. At most k zeros can become ones.",
      objective: "Find the longest window of 1s achievable with k replacements.",
      constraint: "Track zeroes in window. Shrink when zeroes > k.",
      sceneLabel: "◇ SCANNER DISTRICT · LONGEST ONES WITH K FLIPS",
    },
    7: {
      missionName: "RAIN CATCHER",
      zone: "Scanner District",
      situation: "A signal stream with noise spikes.",
      objective: "Find the minimum-length subarray whose sum is ≥ target.",
      constraint: "Expand right greedily, shrink left while sum ≥ target.",
      sceneLabel: "◇ SCANNER DISTRICT · MINIMUM SIZE SUBARRAY",
    },
    8: {
      missionName: "ALL ANAGRAMS",
      zone: "Scanner District",
      situation: "A text stream. Count every position an anagram starts.",
      objective: "Return the count (and indices) of all anagram occurrences.",
      constraint: "Fixed window = pattern length. Frequency diff tracks mismatches.",
      sceneLabel: "◇ SCANNER DISTRICT · ALL ANAGRAM POSITIONS",
    },
  },

  "trees": {
    1: {
      missionName: "SEED PLANTER",
      zone: "Tree Temple",
      situation: "Tree Temple. A binary search tree of ancient keys.",
      objective: "Plant the new key at its correct leaf slot.",
      constraint: "left < node < right. Follow the path down. O(h).",
      sceneLabel: "◇ TREE TEMPLE · BST INSERT",
    },
    2: {
      missionName: "NODE HUNT",
      zone: "Tree Temple",
      situation: "A BST with values scattered across branches.",
      objective: "Navigate to the target value by comparing at each node.",
      constraint: "Go left if smaller, right if larger. O(h) per search.",
      sceneLabel: "◇ TREE TEMPLE · BST SEARCH",
    },
    3: {
      missionName: "IN-ORDER WALK",
      zone: "Tree Temple",
      situation: "A BST that encodes a sorted sequence in-order.",
      objective: "Visit all nodes in in-order (left → root → right) traversal.",
      constraint: "In-order traversal of a BST yields sorted output.",
      sceneLabel: "◇ TREE TEMPLE · IN-ORDER TRAVERSAL",
    },
    4: {
      missionName: "LEVEL RAIN",
      zone: "Tree Temple",
      situation: "A tree with values at each level. Top-down scan.",
      objective: "Visit every node level by level using BFS on the tree.",
      constraint: "Queue-based BFS. Process all nodes at current depth before next.",
      sceneLabel: "◇ TREE TEMPLE · LEVEL-ORDER TRAVERSAL",
    },
    5: {
      missionName: "LCA CLIMBER",
      zone: "Tree Temple",
      situation: "Two nodes in a BST. Find their meeting point.",
      objective: "Find the Lowest Common Ancestor of two target nodes.",
      constraint: "If both targets < node → go left. Both > node → go right. Else = LCA.",
      sceneLabel: "◇ TREE TEMPLE · LOWEST COMMON ANCESTOR",
    },
    6: {
      missionName: "BST JUDGE",
      zone: "Tree Temple",
      situation: "A tree that may or may not satisfy BST invariants.",
      objective: "Identify the node that violates the BST property.",
      constraint: "Track valid range [min, max] at each node. Out-of-range = violation.",
      sceneLabel: "◇ TREE TEMPLE · BST VALIDATION",
    },
    7: {
      missionName: "NODE REMOVER",
      zone: "Tree Temple",
      situation: "A BST with a node marked for deletion.",
      objective: "Delete the target node while preserving BST structure.",
      constraint: "Two-child case: replace with in-order successor.",
      sceneLabel: "◇ TREE TEMPLE · BST DELETE",
    },
    8: {
      missionName: "PATH TRACER",
      zone: "Tree Temple",
      situation: "A tree with weighted nodes. One path sums to target.",
      objective: "Trace the root-to-leaf path whose node values sum to the target.",
      constraint: "DFS: subtract node value, check zero at leaf.",
      sceneLabel: "◇ TREE TEMPLE · PATH SUM",
    },
  },

  "tries": {
    1: {
      missionName: "LETTER DROP",
      zone: "Trie Archives",
      situation: "Trie Archives. A prefix tree of indexed words.",
      objective: "Insert the word letter by letter; mark the word-end node.",
      constraint: "Reuse shared prefixes. O(m) per word, m = length.",
      sceneLabel: "◇ TRIE ARCHIVES · TRIE INSERT",
    },
    2: {
      missionName: "PREFIX SCOUT",
      zone: "Trie Archives",
      situation: "A trie holding thousands of words. A query prefix arrives.",
      objective: "Search the trie and confirm the prefix exists.",
      constraint: "Walk the trie one char at a time. Missing node = not found.",
      sceneLabel: "◇ TRIE ARCHIVES · PREFIX SEARCH",
    },
    3: {
      missionName: "WORD SEEKER",
      zone: "Trie Archives",
      situation: "A trie holding an indexed lexicon.",
      objective: "Search for the full word and confirm it ends at a word-end node.",
      constraint: "Prefix match is not enough — must reach a word-end marker.",
      sceneLabel: "◇ TRIE ARCHIVES · EXACT WORD SEARCH",
    },
    4: {
      missionName: "AUTO SUGGEST",
      zone: "Trie Archives",
      situation: "A trie powers an autocomplete engine.",
      objective: "Given a prefix, find all words that start with it.",
      constraint: "DFS from prefix node. Collect every word-end node below.",
      sceneLabel: "◇ TRIE ARCHIVES · AUTOCOMPLETE DFS",
    },
    5: {
      missionName: "COMMON FORK",
      zone: "Trie Archives",
      situation: "Two word sets share prefixes in the trie.",
      objective: "Find the longest common prefix shared by all words.",
      constraint: "Walk while all words share the same char. Stop at any fork.",
      sceneLabel: "◇ TRIE ARCHIVES · LONGEST COMMON PREFIX",
    },
    6: {
      missionName: "ROOT CUTTER",
      zone: "Trie Archives",
      situation: "A sentence. Words have root forms in a dictionary trie.",
      objective: "Replace each word with its shortest root from the trie.",
      constraint: "Scan each word: walk trie to first word-end = its root.",
      sceneLabel: "◇ TRIE ARCHIVES · WORD REPLACEMENT",
    },
    7: {
      missionName: "SENTENCE SLICER",
      zone: "Trie Archives",
      situation: "A string with no spaces. A dictionary trie holds valid words.",
      objective: "Determine if the string can be segmented into dictionary words.",
      constraint: "DP + trie: dp[i] = true if some dp[j] is true and s[j:i] is in trie.",
      sceneLabel: "◇ TRIE ARCHIVES · WORD BREAK DP",
    },
    8: {
      missionName: "WILD MATCHER",
      zone: "Trie Archives",
      situation: "A trie with wildcard queries using '.' as any-char.",
      objective: "Answer queries where '.' matches any single character.",
      constraint: "Wildcard '.' requires branching into all child nodes at that depth.",
      sceneLabel: "◇ TRIE ARCHIVES · WILDCARD SEARCH",
    },
  },

  "dynamic-programming": {
    1: {
      missionName: "FROG LEAP",
      zone: "DP Lab",
      situation: "DP Lab. A frog on stepping stones. Each jump: +1 or +2.",
      objective: "Count all distinct ways to reach the top.",
      constraint: "dp[i] = dp[i-1] + dp[i-2]. Build bottom-up.",
      sceneLabel: "◇ DP LAB · CLIMBING STAIRS",
    },
    2: {
      missionName: "VAULT CRACKER",
      zone: "DP Lab",
      situation: "A vault with items of weight and value. Limited capacity.",
      objective: "Maximize total value without exceeding the weight limit.",
      constraint: "0/1 Knapsack: dp[i][w] = max(skip, take). Build table.",
      sceneLabel: "◇ DP LAB · 0/1 KNAPSACK",
    },
    3: {
      missionName: "COIN FORGE",
      zone: "DP Lab",
      situation: "DP Lab. A target amount and a set of coin denominations.",
      objective: "Fill the table: fewest coins to forge each amount.",
      constraint: "dp[a] = min(dp[a-coin] + 1) for each coin. Bottom-up.",
      sceneLabel: "◇ DP LAB · COIN CHANGE",
    },
    4: {
      missionName: "GENE SPLICE",
      zone: "DP Lab",
      situation: "Two DNA strands. Find their longest shared subsequence.",
      objective: "Compute the Longest Common Subsequence of two strings.",
      constraint: "dp[i][j] = dp[i-1][j-1]+1 if match, else max(dp[i-1][j], dp[i][j-1]).",
      sceneLabel: "◇ DP LAB · LONGEST COMMON SUBSEQUENCE",
    },
    5: {
      missionName: "LOOT PACK",
      zone: "DP Lab",
      situation: "A robbery route. Adjacent houses trigger the alarm.",
      objective: "Rob the maximum value without triggering adjacent alarms.",
      constraint: "dp[i] = max(dp[i-1], dp[i-2] + nums[i]). Skip or rob.",
      sceneLabel: "◇ DP LAB · HOUSE ROBBER",
    },
    6: {
      missionName: "PIXEL PATH",
      zone: "DP Lab",
      situation: "A grid with movement costs. Start top-left, reach bottom-right.",
      objective: "Find the path with minimum total cost from (0,0) to (m,n).",
      constraint: "dp[i][j] = grid[i][j] + min(dp[i-1][j], dp[i][j-1]).",
      sceneLabel: "◇ DP LAB · MIN COST PATH",
    },
    7: {
      missionName: "WORD WARP",
      zone: "DP Lab",
      situation: "Two words. One must transform into the other via edits.",
      objective: "Find the minimum edit distance (insert, delete, replace).",
      constraint: "dp[i][j] = edit cost using first i and j chars of each word.",
      sceneLabel: "◇ DP LAB · EDIT DISTANCE",
    },
    8: {
      missionName: "MIRROR GEM",
      zone: "DP Lab",
      situation: "A string hiding palindromic subsequences within.",
      objective: "Find the longest palindromic subsequence.",
      constraint: "dp[i][j] = dp[i+1][j-1]+2 if match, else max(dp[i+1][j], dp[i][j-1]).",
      sceneLabel: "◇ DP LAB · LONGEST PALINDROMIC SUBSEQUENCE",
    },
  },
};

export function getMission(module: string, gameIndex: number): GameMission {
  return GAME_MISSIONS[module]?.[gameIndex] ?? {
    missionName: "MISSION",
    zone: "ZONE",
    situation: "Navigate the challenge.",
    objective: "Solve the problem.",
    constraint: "Apply the optimal algorithm.",
    sceneLabel: "◇ GAME",
  };
}

export function getTools(module: string): ShellTool[] {
  return MODULE_TOOLS[module] ?? [];
}
